=head1 NAME

pacutils - utility library for libalpm front-ends

=head1 SYNOPSIS

 pu_config_t *config = pu_config_new_from_file("/etc/pacman.conf");
 alpm_handle_t *handle = pu_initialize_handle_from_config(config);
 alpm_list_t *syncdbs = pu_register_syncdbs(config->repos);

 alpm_option_set_progresscb(handle, pu_cb_progress);
 alpm_option_set_dlcb(handle, pu_cb_download);

 /* do something with handle... */

 alpm_list_free(sync_dbs);
 alpm_release(handle);
 pu_config_free(config);

B<pacutils> encapsulates several of the common tasks that most users of
I<libalpm> need to perform, such as parsing F<pacman.conf> and providing
standard output functions for callbacks.  The included programs can also be
used as guides for how to accomplish particular tasks using I<libalpm>.

=head1 DESCRIPTION

=head2 Configuration Parsing

=over

=item pu_config_t *pu_config_new_from_file(const char *filename);

Parse a I<pacman> configuration file into a C<pu_config_t> structure.  B<Note:>
this is the final configuration as parsed by I<pacman>.  C<Include> directives
will be processed, defaults are set, C<$repo> and C<$arch> will be replaced in
C<Server> directives and C<Architecture> will be replaced if set to C<auto>.

=item void pu_config_free(pu_config_t *config);

=item alpm_handle_t *pu_initialize_handle_from_config(pu_config_t *config);

=back

=head2 Repositories

=over

=item alpm_db_t *pu_register_syncdb(pu_repo_t *repo);

=item alpm_list_t *pu_register_syncdbs(alpm_list_t *repos);

=item void pu_repo_free(pu_repo_t *repo);

=back

=head2 Callbacks

=over

=item const char *pu_msg_progress(alpm_progress_t event);

=item void pu_cb_progress(alpm_progress_t event, const char *pkgname,
            int percent, size_t total, size_t current);

=item void pu_cb_download(const char *filename, off_t xfered, off_t total);

=back

=head2 Pkgspec

A C<pkgspec> is a string consisting of sufficient information to uniquely
identify an individual package.  Currently recognized formats are:

=over

=item <dbname>/<pkgname>

 local/pacman
 core/pacman

=item <protocol>://<path>

 ftp://ftp.archlinux.org/core/os/x86_64/pacman-4.1.2-5-x86_64.pkg.tar.xz
 file:///var/cache/pacman/pkg/pacman-4.1.2-5-x86_64.pkg.tar.xz

=back

=head1 PROGRAMS

There are several programs located in F<src/>.  Refer to each program's
documentation for more information.

=over

=item pacconf

Query I<pacman>'s configuration file.  Useful for shell scripts:

 dbpath=$(pacconf dbpath)
 color=$(pacconf color)
 [[ -n $color ]] && ... # print something in color

B<Note:> this is the final configuration as parsed by I<pacman>.  C<Include>
directives will be processed, defaults are set, C<$repo> and C<$arch> will be
replaced in C<Server> directives and C<Architecture> will be replaced if set to
C<auto>.

=item pacsync

Updates repository databases.  Equivalent to C<pacman -Sy>.

=item pactrans/pacinstall/pacremove

Install/remove packages in a single transaction.

B<NOTE:> I<alpm> support for installation and removal in a single transaction
is flaky; some options may be ignored.

=item pacinfo

Display information for packages, similar to C<pacman -Qi> and C<pacman -Si>.
Input should be a list of pkgspecs.

B<EXPERIMENTAL:> If a package name is given instead of a pkgspec, all packages
in all databases with the given name will be displayed.

=item pacsift

Package search/filter tool.  Combine with B<pacinfo> to display brief package
information similar to C<pacman -Qs> and C<pacman -Ss>:

 pacsift --name pacman | pacinfo --short

=item pacfile

Display information about a file.  Includes information from C<pacman -Qo>,
C<pacman -Qkk>, and C<pacman -Qii>.  Expects input to match the path stored in
B<pacman>'s database with or without the root prepended.  I<realpath> can be
used to call with relative paths or paths containing symbolic links:

 pacfile "$(realpath ./foo)"

=item paclog

Filter pacman log entries.  If multiple filters are provided, the entries
returned are the union of all filters.  Output can be piped to a second
instance to find the intersection of filters instead:

 paclog --caller ALPM | paclog --after 2014-04-06

=back

=head1 BUGS

Not implemented yet:

=over

=item globs in Include directives

=item error reporting

=item siglevel inheritance for repos and local/remote values

=item proper handling of transaction flags with combined transactions

=back

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2012-2014 Andrew Gregory

pacutils is distributed under the terms of the MIT license.  See F<COPYING> for
details.
