=head1 NAME

paccheck - check installed packages

=head1 SYNOPSIS

 paccheck [options] [<package>]...
 paccheck (--help|--version)

=head1 DESCRIPTION

Check installed packages.  Passing a single dash (C<->) as an argument is will
read package names from F<stdin>, equivalent to passing C<--read-fd=0>. If no
package are provided, all installed packages will be checked.  By default only
package dependencies and basic file information will checked.

=head1 OPTIONS

=over

=item B<--config>=F<path>

Set an alternate configuration file path.

=item B<--dbpath>=F<path>

Set an alternate database path.

=item B<--root>=F<path>

Set an alternate installation root.

=item B<--sysroot>=F<path>

Set an alternate system root.  See L<pacutils-sysroot(7)>.

=item B<--read-fd>=I<fd>

Read package names from file descriptor I<fd>. Packages are read immediately
upon encountering the option using any separator previously set with B<--null>.

=item B<--read-file>=F<path>

Read package names from file F<path>. Packages are read immediately
upon encountering the option using any separator previously set with B<--null>.

=item B<--null>[=I<sep>]

Use C<NUL> as the separator when parsing values from input streams instead of
C<\n>. An optional argument I<sep> may be used to specify a separator other
than C<NUL>.

=item B<--list-broken>

Only print the names of packages that fail the selected checks.

=item B<--quiet>

Only display messages if a problem is found.

=item B<--recursive>

Recursively perform checks on packages' dependencies as well.

=item B<--depends>

Check that all package dependencies are satisfied.

=item B<--opt-depends>

Check that all package optional dependencies are satisfied.

=item B<--files>

Check package files against the local database.

=item B<--file-properties>

Check package files against MTREE data.

=item B<--md5sum>

Check file md5sums against MTREE data.

=item B<--sha256sum>

Check file sha256sums against MTREE data.

=item B<--require-mtree>

Treat missing MTREE data as an error for B<--db-files> and/or
B<--file-properties>.

=item B<--db-files>

Include database files in B<--files> and B<--file-properties> checks.
B<--files> will test for the existence of F<desc>, F<files>, and F<mtree> (with
B<--require-mtree>) files in the package database entry.  B<--file-properties>
will check F<install> and F<changelog> files in the package database where
applicable.

=item B<--backup>

Include backup files in file modification checks.

=item B<--noextract>

Include NoExtract files in file modification checks.

=item B<--noupgrade>

Include NoUpgrade files in file modification checks.

=item B<--help>

Display usage information and exit.

=item B<--version>

Display version information and exit.

=back
