=head1 NAME

pacfile - display information about package files

=head1 SYNOPSIS

 pacfile [options] <path>...
 pacfile (--help|--version)

An argument of C<-> may be provided to read the list of paths from
standard input, equivalent to C<--read-fd=0>.

=head1 DESCRIPTION

Display file information from the local package database.

=head1 OPTIONS

=over

=item B<--config>=F<path>

Set an alternate configuration file path.

=item B<--dbpath>=F<path>

Set an alternate database path.

=item B<--root>=F<path>

Set an alternate installation root.

=item B<--sysroot>=F<path>

Set an alternate system root.  See L<pacutils-sysroot(7)>.

=item B<--read-fd>=I<fd>

Read paths from I<fd>.  NOTE: targets are read immediately upon
encountering this option.

=item B<--read-file>=I<path>

Read targets from I<path>.  NOTE: targets are read immediately upon
encountering this option.

=item B<--package>=I<pkgname>

Limit information to the specified package.  May be specified multiple times.

=item B<--check>

Compare database values to the file system.

=item B<--help>

Display usage information and exit.

=item B<--version>

Display version information and exit.

=back
