=head1 NAME

pacrepairfile - reset properties on alpm-managed files

=head1 SYNOPSIS

 pacrepairfile [options] (--gid|--mode|--mtime|--uid)... <file>...
 pacrepairfile (--help|--version)

=head1 DESCRIPTION

Resets file properties for alpm-managed files based on MTREE data.

=head1 OPTIONS

=over

=item B<--config>=F<path>

Set an alternate configuration file path.

=item B<--dbpath>=F<path>

Set an alternate database path.

=item B<--root>=F<path>

Set an alternate installation root.

=item B<--sysroot>=F<path>

Set an alternate system root.  See L<pacutils-sysroot(7)>.

=item B<--quiet>

Do not display progress information.

=item B<--package>=I<pkgname>

Search I<pkgname> for file properties.  May be specified multiple times.  If
B<--package> is not specified, all installed packages will be searched.

=item B<--help>

Display usage information and exit.

=item B<--version>

Display version information and exit.

=back

=head2 Fields

=over

=item B<--gid>

Reset file owner group id.

=item B<--mode>

Reset file permissions.

=item B<--mtime>

Reset file modification time.

=item B<--uid>

Reset file owner user id.

=back
