#!/usr/bin/sh

r="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -d "$r" ] && cd "$r"; then
    git subtree pull --squash --prefix=ext/tap.c https://github.com/andrewgregory/tap.c.git master
else
    printf >2 "unable to chdir to repository root '%s'\n" "$r"
    exit 1
fi
