#!/usr/bin/sh

r="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -d "$r" ] && cd "$r"; then
  git subtree pull --squash --prefix=ext/globdir.c https://github.com/andrewgregory/globdir.c.git master
  git subtree pull --squash --prefix=ext/mini.c    https://github.com/andrewgregory/mini.c.git master
  git subtree pull --squash --prefix=ext/tap.c     https://github.com/andrewgregory/tap.c.git master
else
  printf "unable to chdir to repository root '%s'\n" "$r"
  exit 1
fi
